use crate::{
    attacks::JammingAttack, clock::InstantClock, reputation_interceptor::ReputationMonitor,
    BoxError,
};
use async_trait::async_trait;
use bitcoin::secp256k1::PublicKey;
use lightning::{ln::PaymentHash, routing::gossip::NetworkGraph};
use ln_resource_mgr::forward_manager::SimulationDebugManager;
use rand::seq::SliceRandom;
use sim_cli::parsing::NetworkParser;
use simln_lib::{
    clock::Clock,
    sim_node::{SimGraph, SimNode, WrappedLog},
};
use std::{collections::HashMap, sync::Arc};
use triggered::Listener;

use super::utils::build_custom_route;

// idea: attacker1 -> peer1 -> target -> attacker2
// build reputation on attacker2 and jam channel peer1 <-> target
// do that for all target's channels

pub struct SlowJam<'a, C, J, R>
where
    C: Clock + InstantClock,
    R: ReputationMonitor + Send + Sync,
    J: SimulationDebugManager,
{
    clock: Arc<C>,
    target_pubkey: PublicKey,
    attacker_pubkey: PublicKey,
    target_channels: HashMap<u64, PublicKey>,
    reputation_monitor: Arc<R>,
    general_jammer: Arc<J>,
    network_graph: Arc<NetworkGraph<&'a WrappedLog>>,
    // TODO: add hashmap mutex to keep track of sent payments.
    // if payment generated by us, then in intercepted just let it go through
}

impl<'a, C, J, R> SlowJam<'a, C, J, R>
where
    C: Clock + InstantClock,
    R: ReputationMonitor + Send + Sync,
    J: SimulationDebugManager,
{
    pub fn new(
        clock: Arc<C>,
        network: &[NetworkParser],
        target_pubkey: PublicKey,
        attacker_pubkey: PublicKey,
        reputation_monitor: Arc<R>,
        general_jammer: Arc<J>,
        network_graph: Arc<NetworkGraph<&'a WrappedLog>>,
    ) -> Self {
        Self {
            clock,
            target_pubkey,
            attacker_pubkey,
            target_channels: HashMap::from_iter(network.iter().filter_map(|channel| {
                if channel.node_1.pubkey == target_pubkey {
                    Some((channel.scid.into(), channel.node_2.pubkey))
                } else if channel.node_2.pubkey == target_pubkey {
                    Some((channel.scid.into(), channel.node_1.pubkey))
                } else {
                    None
                }
            })),
            reputation_monitor,
            general_jammer,
            network_graph,
        }
    }

    async fn build_reputation<'b>(
        &self,
        //attacker_nodes: Arc<Mutex<HashMap<PublicKey, SimNode<'b, SimGraph>>>>,
        attacker_node: &mut SimNode<'b, SimGraph>,
        peer: &PublicKey,
    ) -> Result<(), BoxError> {
        let channel = self
            .target_channels
            .iter()
            .find(|chan| peer == chan.1)
            .ok_or(format!("Peer {} does not have a channel with target", peer))?
            .0;

        let batch_size = 500;
        let payment_amt_msat = 10_000;

        // route: attacker -> peer -> target -> attacker
        let hops = vec![
            self.attacker_pubkey,
            *peer,
            self.target_pubkey,
            self.attacker_pubkey,
        ];
        let rev_hops: Vec<PublicKey> = hops.clone().into_iter().rev().collect();

        let route = build_custom_route(
            &self.attacker_pubkey,
            payment_amt_msat,
            &hops,
            &self.network_graph,
        )
        .map_err(|e| {
            log::error!("Error {} building route through peer {}", e.err, peer);
            e.err
        })?;

        let rev_route = build_custom_route(
            &self.attacker_pubkey,
            payment_amt_msat,
            &rev_hops,
            &self.network_graph,
        )
        .map_err(|e| {
            log::error!("Error {} building route through peer {}", e.err, peer);
            e.err
        })?;

        loop {
            // Send batch of payments that should succeed to build reputation.
            for _ in 0..batch_size {
                let mut payment_hash = [0u8; 32];
                payment_hash.shuffle(&mut rand::rng());

                if let Err(e) = attacker_node
                    .send_to_route(route.clone(), PaymentHash(payment_hash))
                    .await
                {
                    log::error!("Payment with custom route failed {:?}", e);
                }

                let mut payment_hash = [0u8; 32];
                payment_hash.shuffle(&mut rand::rng());
                if let Err(e) = attacker_node
                    .send_to_route(rev_route.clone(), PaymentHash(payment_hash))
                    .await
                {
                    log::error!("Payment with custom route failed {:?}", e);
                }
            }

            // After batch of payments, check if sufficient reputation and if so break out of loop.
            // If not, send another batch.
            let channel_reputations = self
                .reputation_monitor
                .list_channels(self.target_pubkey, InstantClock::now(&*self.clock))
                .await?;
            let channel_snapshot = channel_reputations
                .get(&channel)
                .ok_or(format!("Channel {} not found", channel))?; // this shouldn't happen

            if channel_snapshot.outgoing_reputation > channel_snapshot.bidirectional_revenue {
                println!("FINISHED BUILDING REPUTATION!");
                return Ok(());
            }

            // thread::sleep(Duration::from_millis(100));
        }
    }
}

#[async_trait]
impl<'a, C, J, R> JammingAttack for SlowJam<'a, C, J, R>
where
    C: Clock + InstantClock,
    R: ReputationMonitor + Send + Sync,
    J: SimulationDebugManager + Send + Sync,
{
    async fn run_custom_actions<'b>(
        &self,
        mut attacker_nodes: HashMap<PublicKey, SimNode<'b, SimGraph>>,
        _shutdown_listener: Listener,
    ) -> Result<(), BoxError> {
        // - Build reputation (send payment in batches and check every now and then if it has built
        // sufficient reputation)
        // - after building reputation, jam general resources.
        // - use congestion
        // - with sufficient reputation, continuously jam protected resources by sending payments
        // slow (80s) resolving payments that don't slash reputation.

        // NOTE: first just try to jam one channel instead of the entire node.
        let mut target_channel = None;
        for (scid, peer_pubkey) in &self.target_channels {
            let attacker_node = attacker_nodes.get_mut(&self.attacker_pubkey).unwrap();
            self.build_reputation(attacker_node, peer_pubkey)
                .await
                .unwrap();
            target_channel = Some(*scid);
            break;
        }

        // after building reputation, jam general resources.
        self.general_jammer
            .general_jam_channel(target_channel.unwrap())
            .unwrap();

        // with reputation, jam protected resources by sending 80s resolving payments continuously.
        //  send payments from multiple channels to use congestion resources.
        Ok(())
    }
}
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
