use crate::{
    accountable_from_records,
    attacks::JammingAttack,
    clock::InstantClock,
    records_from_signal,
    reputation_interceptor::{GeneralChannelJammer, ReputationMonitor},
    BoxError,
};

use async_trait::async_trait;
use bitcoin::secp256k1::PublicKey;
use lightning::{ln::PaymentHash, routing::gossip::NetworkGraph};
use rand::Rng;
use sim_cli::parsing::NetworkParser;
use simln_lib::{
    clock::Clock,
    sim_node::{
        CustomRecords, ForwardingError, HtlcRef, InterceptRequest, SimGraph, SimNode, WrappedLog,
    },
};
use std::{collections::HashMap, str::FromStr, sync::Arc};
use tokio::sync::Mutex;
use triggered::Listener;

use super::utils::{build_custom_route, build_reputation};

// idea: attacker1 -> peer1 -> target -> attacker2
// build reputation on attacker2 and jam channel peer1 <-> target
// do that for all target's channels

type LdkNetworkGraph = NetworkGraph<Arc<WrappedLog>>;

pub struct SlowJam<C, J, R>
where
    C: Clock + InstantClock,
    R: ReputationMonitor + Send + Sync,
    J: GeneralChannelJammer + Send + Sync,
{
    clock: Arc<C>,
    target_pubkey: PublicKey,
    attacker: (String, PublicKey),
    target_channels: HashMap<u64, PublicKey>,
    reputation_monitor: Arc<Mutex<R>>,
    general_jammer: Arc<Mutex<J>>,
    //network_graph: Arc<NetworkGraph<&'a WrappedLog>>,
    network_graph: Arc<LdkNetworkGraph>,
    // if payment generated by us, then in intercepted just let it go through
    //our_payments: HashMap<HtlcRef, PaymentHash>,
    our_payments: Mutex<HashMap<PaymentHash, Option<HtlcRef>>>,
}

impl<C, J, R> SlowJam<C, J, R>
where
    C: Clock + InstantClock,
    R: ReputationMonitor + Send + Sync,
    J: GeneralChannelJammer + Send + Sync,
{
    pub fn new(
        clock: Arc<C>,
        network: &[NetworkParser],
        target_pubkey: PublicKey,
        attacker: (String, PublicKey),
        reputation_monitor: Arc<Mutex<R>>,
        general_jammer: Arc<Mutex<J>>,
        network_graph: Arc<LdkNetworkGraph>,
    ) -> Self {
        Self {
            clock,
            target_pubkey,
            attacker,
            target_channels: HashMap::from_iter(network.iter().filter_map(|channel| {
                if channel.node_1.pubkey == target_pubkey {
                    Some((channel.scid.into(), channel.node_2.pubkey))
                } else if channel.node_2.pubkey == target_pubkey {
                    Some((channel.scid.into(), channel.node_1.pubkey))
                } else {
                    None
                }
            })),
            reputation_monitor,
            general_jammer,
            network_graph,
            our_payments: Mutex::new(HashMap::new()),
        }
    }

    async fn build_reputation(
        &self,
        attacker_nodes: HashMap<String, Arc<Mutex<SimNode<SimGraph>>>>,
        target_pubkey: PublicKey,
    ) -> Result<(), BoxError> {
        let payment_amt_msat = 20_000_000;

        // target channel 348545186070528
        let intermediate_peer = PublicKey::from_str(
            "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
        )
        .unwrap();

        // alias 25
        let from_attacker = PublicKey::from_str(
            "033dbb3f4662640d4888918eeb986069b9b775c921b9ec6debcada1b3ac58a1b0b",
        )
        .unwrap();

        let to_attacker = PublicKey::from_str(
            "035a43121d24b2ff465e85af9c07963701f259b5ce4ee636e3aeb503cc64142c11",
        )
        .unwrap();

        let from_attacker_channel = self
            .target_channels
            .iter()
            .find(|chan| from_attacker == *chan.1)
            .ok_or(format!(
                "Target does not have a channel with {}",
                to_attacker
            ))?
            .0;

        let to_attacker_channel = self
            .target_channels
            .iter()
            .find(|chan| to_attacker == *chan.1)
            .ok_or(format!(
                "Target does not have a channel with {}",
                to_attacker
            ))?
            .0;

        // route: attacker -> peer -> target -> attacker
        //let hops = vec![intermediate_peer, self.target_pubkey, to_attacker];
        let hops = vec![self.target_pubkey, to_attacker];

        let from_attacker = attacker_nodes.get("25").unwrap();
        // "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",

        let target_channel_scid = 348545186070528;
        let peer_pubkey = PublicKey::from_str(
            "0353325e099c2b657ca5c4bb975a20b0c3de1d2391dabe73f40484aac255628d22",
        )
        .unwrap();
        let target_channel = (peer_pubkey, target_channel_scid);
        let fees_paid = build_reputation(
            Arc::clone(&from_attacker),
            &hops,
            &self.network_graph,
            vec![10_000_000],
            24792749238,
            target_channel,
            Arc::clone(&self.reputation_monitor),
            Arc::clone(&self.clock),
        )
        .await?;

        let target_channel_snapshots = self
            .reputation_monitor
            .lock()
            .await
            .list_channels(self.target_pubkey, InstantClock::now(&*self.clock))
            .await?;

        let to_attacker_channel_snapshot = target_channel_snapshots
            .get(to_attacker_channel)
            .ok_or(format!("Channel {} not found", to_attacker_channel))?; // this shouldn't happen

        let peer_target_channel = target_channel_snapshots
            .get(&target_channel_scid)
            .ok_or(format!("Channel {} not found", to_attacker_channel))?;

        println!(
            "PEER-TARGET CHANNEL REVENUW {}",
            peer_target_channel.bidirectional_revenue
        );

        println!(
            "OUTGOING REPUTATION {}",
            to_attacker_channel_snapshot.outgoing_reputation
        );

        if to_attacker_channel_snapshot.outgoing_reputation
            >= peer_target_channel.bidirectional_revenue + 2666000
        {
            println!(
                "Finished building reputation. It cost {} in fees",
                fees_paid
            );
            return Ok(());
        }

        Err("could not build reputation".into())
        //Ok(())
    }

    // async fn build_reputation(
    //     &self,
    //     attacker_nodes: HashMap<String, Arc<Mutex<SimNode<SimGraph>>>>,
    //     peer: &PublicKey,
    // ) -> Result<(), BoxError> {
    //     let batch_size = 250;
    //     let payment_amt_msat = 20_000_000;
    //
    //     let intermediate_peer = PublicKey::from_str(
    //         "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
    //     )
    //     .unwrap();
    //
    //     let from_attacker = PublicKey::from_str(
    //         "033dbb3f4662640d4888918eeb986069b9b775c921b9ec6debcada1b3ac58a1b0b",
    //     )
    //     .unwrap();
    //
    //     let from_attacker_2 = PublicKey::from_str(
    //         "035b1ff29e8db1ba8f2a4f4f95db239b54069cb949b8cde329418e2a83da4f1b30",
    //     )
    //     .unwrap();
    //
    //     let to_attacker = PublicKey::from_str(
    //         "035a43121d24b2ff465e85af9c07963701f259b5ce4ee636e3aeb503cc64142c11",
    //     )
    //     .unwrap();
    //
    //     let from_attacker_channel = self
    //         .target_channels
    //         .iter()
    //         .find(|chan| from_attacker == *chan.1)
    //         .ok_or(format!(
    //             "Target does not have a channel with {}",
    //             to_attacker
    //         ))?
    //         .0;
    //
    //     let to_attacker_channel = self
    //         .target_channels
    //         .iter()
    //         .find(|chan| to_attacker == *chan.1)
    //         .ok_or(format!(
    //             "Target does not have a channel with {}",
    //             to_attacker
    //         ))?
    //         .0;
    //
    //     // route: attacker -> peer -> target -> attacker
    //     //let hops = vec![intermediate_peer, self.target_pubkey, to_attacker];
    //     let hops = vec![self.target_pubkey, to_attacker];
    //     let route = build_custom_route(
    //         &from_attacker,
    //         payment_amt_msat,
    //         &hops,
    //         self.network_graph.as_ref(),
    //     )
    //     .map_err(|e| {
    //         log::error!("Error {} building route through peer {}", e.err, peer);
    //         e.err
    //     })?;
    //
    //     let hops_2 = vec![self.target_pubkey, to_attacker];
    //     let route_2 = build_custom_route(
    //         &from_attacker_2,
    //         payment_amt_msat,
    //         &hops_2,
    //         self.network_graph.as_ref(),
    //     )
    //     .map_err(|e| {
    //         log::error!("Error {} building route through peer {}", e.err, peer);
    //         e.err
    //     })?;
    //
    //     //let rev_hops = vec![self.target_pubkey, intermediate_peer, from_attacker];
    //     let rev_hops = vec![self.target_pubkey, from_attacker];
    //     let rev_route = build_custom_route(
    //         &to_attacker,
    //         payment_amt_msat,
    //         &rev_hops,
    //         &self.network_graph,
    //     )
    //     .map_err(|e| {
    //         log::error!("Error {} building route through peer {}", e.err, peer);
    //         e.err
    //     })?;
    //
    //     let rev_hops_2 = vec![self.target_pubkey, from_attacker_2];
    //     let rev_route_2 = build_custom_route(
    //         &to_attacker,
    //         payment_amt_msat,
    //         &rev_hops_2,
    //         &self.network_graph,
    //     )
    //     .map_err(|e| {
    //         log::error!("Error {} building route through peer {}", e.err, peer);
    //         e.err
    //     })?;
    //
    //     loop {
    //         // Send batch of payments that should succeed to build reputation.
    //         for _ in 0..batch_size {
    //             let from_attacker = attacker_nodes.get(&from_attacker).unwrap();
    //
    //             let hash_1 = PaymentHash(get_random_bytes());
    //             let mut a = from_attacker.lock().await;
    //             if let Err(e) = a.send_to_route(route.clone(), hash_1, None).await {
    //                 log::error!("Payment with custom route failed 1 {:?}", e);
    //             }
    //
    //             let from_attacker_2 = attacker_nodes.get(&from_attacker_2).unwrap();
    //             let hash_2 = PaymentHash(get_random_bytes());
    //             let mut a = from_attacker_2.lock().await;
    //             if let Err(e) = a.send_to_route(route_2.clone(), hash_2, None).await {
    //                 log::error!("Payment with custom route failed 1 {:?}", e);
    //             }
    //
    //             let to_attacker = attacker_nodes.get(&to_attacker).unwrap();
    //             let hash_2 = PaymentHash(get_random_bytes());
    //             if let Err(e) = to_attacker
    //                 .lock()
    //                 .await
    //                 .send_to_route(rev_route.clone(), hash_2, None)
    //                 .await
    //             {
    //                 log::error!("Payment with custom route failed 2 {:?}", e);
    //             }
    //
    //             let hash_2 = PaymentHash(get_random_bytes());
    //             if let Err(e) = to_attacker
    //                 .lock()
    //                 .await
    //                 .send_to_route(rev_route_2.clone(), hash_2, None)
    //                 .await
    //             {
    //                 log::error!("Payment with custom route failed 2 {:?}", e);
    //             }
    //
    //             //thread::sleep(Duration::from_millis(50));
    //         }
    //
    //         thread::sleep(Duration::from_millis(200));
    //
    //         // After batch of payments, check if sufficient reputation and if so break out of loop.
    //         // If not, send another batch.
    //         let channel_reputations = self
    //             .reputation_monitor
    //             .list_channels(self.target_pubkey, InstantClock::now(&*self.clock))
    //             .await?;
    //
    //         let to_attacker_channel_snapshot = channel_reputations
    //             .get(to_attacker_channel)
    //             .ok_or(format!("Channel {} not found", to_attacker_channel))?; // this shouldn't happen
    //
    //         // println!(
    //         //     "TO ATTACKER CHANNEL SNAPSHOT {:?}",
    //         //     to_attacker_channel_snapshot
    //         // );
    //
    //         let from_attacker_channel_snapshot = channel_reputations
    //             .get(from_attacker_channel)
    //             .ok_or(format!("Channel {} not found", from_attacker_channel))?; // this shouldn't happen
    //
    //         // println!(
    //         //     "FROM ATTACKER CHANNEL SNAPSHOT {:?}",
    //         //     from_attacker_channel_snapshot
    //         // );
    //
    //         println!(
    //             "OUTGOING REPUTATION {}",
    //             to_attacker_channel_snapshot.outgoing_reputation
    //         );
    //
    //         println!(
    //             "INCOMING REVENUE {}",
    //             from_attacker_channel_snapshot.bidirectional_revenue
    //         );
    //
    //         if to_attacker_channel_snapshot.outgoing_reputation
    //             >= from_attacker_channel_snapshot.bidirectional_revenue + 2666000
    //         {
    //             println!("FINISHED BUILDING REPUTATION!");
    //             process::exit(0);
    //             return Ok(());
    //         }
    //     }
    // }
}

pub fn get_random_bytes() -> [u8; 32] {
    let mut rng = rand::rng();
    let mut bytes = [0u8; 32];
    rng.fill(&mut bytes[..]);
    bytes
}

#[async_trait]
impl<C, J, R> JammingAttack for SlowJam<C, J, R>
where
    C: Clock + InstantClock,
    R: ReputationMonitor + Send + Sync,
    J: GeneralChannelJammer + Send + Sync,
{
    async fn intercept_attacker_htlc(
        &self,
        req: InterceptRequest,
    ) -> Result<Result<CustomRecords, ForwardingError>, BoxError> {
        return Ok(Ok(records_from_signal(accountable_from_records(
            &req.incoming_custom_records,
        ))));
    }

    async fn run_custom_actions(
        &self,
        attacker_nodes: HashMap<String, Arc<Mutex<SimNode<SimGraph>>>>,
        _shutdown_listener: Listener,
    ) -> Result<(), BoxError> {
        // - Build reputation (send payment in batches and check every now and then if it has built
        // sufficient reputation)
        // - after building reputation, jam general resources.
        // - use congestion
        // - with sufficient reputation, continuously jam protected resources by sending slow (80s)
        //  resolving payments that don't slash reputation.

        let mut target_channel = None;
        for (scid, peer_pubkey) in &self.target_channels {
            self.build_reputation(attacker_nodes, *peer_pubkey)
                .await
                .unwrap();
            target_channel = Some((*peer_pubkey, *scid));
            break;
        }

        // after building reputation, jam general resources.
        let target_channel = target_channel.unwrap();
        self.general_jammer
            .lock()
            .await
            .jam_channel(&target_channel.0, target_channel.1)
            .await
            .unwrap();

        // with reputation, jam protected resources by sending 80s resolving payments continuously.
        //  send payments from multiple channels to use congestion resources.
        Ok(())
    }
}
