use bitcoin::secp256k1::PublicKey;
use clap::Parser;
use csv::{ReaderBuilder, StringRecord};
use humantime::Duration as HumanDuration;
use ln_simln_jamming::BoxError;
use ln_simln_jamming::parsing::calc_file_chunks;
use ln_simln_jamming::reputation_interceptor::BootstrapForward;
use std::fs::File;
use std::io::{BufReader, Read, Seek};
use std::ops::Add;
use std::path::PathBuf;
use std::str::FromStr;
use std::time::Duration;
use tokio::runtime::Handle;
use tokio::task::{self};

/// Default file used to describe the network being simulated.
const DEFAULT_SIM_FILE: &str = "./simln.json";

/// Default file used to bootstrap reputation.
const DEFAULT_BOOTSTRAP_FILE: &str = "./bootstrap.csv";

/// Default clock speedup to run with regular wall time.
const DEFAULT_CLOCK_SPEEDUP: &str = "1";

/// The default window that we consider revenue over (2 weeks = 60 * 60 * 24 * 7).
const DEFAULT_REVENUE_WINDOW_SECONDS: &str = "1210000";

/// The default multiplier applied to the revenue window to get reputation window.
const DEFAULT_REPUTATION_MULTIPLIER: &str = "12";

/// The default location to output resulting reputation snapshot.
const DEFAULT_RESULTS_DIR: &str = "./reputation-snapshots";

#[derive(Parser)]
#[command(version, about)]
pub struct Cli {
    /// A json file describing the lightning channels being simulated.
    #[arg(long, short, default_value = DEFAULT_SIM_FILE)]
    pub sim_file: PathBuf,

    /// A CSV file containing forwards for the network, including the attacker used to bootstrap reputation for the
    /// simulation.
    #[arg(long, default_value = DEFAULT_BOOTSTRAP_FILE)]
    pub bootstrap_file: PathBuf,

    /// The duration of time that reputation of the attacking node should be bootstrapped for, expressed as human
    /// readable values (eg: 1w, 3d).
    #[arg(long, value_parser = parse_duration)]
    pub attacker_bootstrap: Option<(String, Duration)>,

    /// Speed up multiplier to add to the wall clock to run the simulation faster.
    #[arg(long, default_value = DEFAULT_CLOCK_SPEEDUP)]
    pub clock_speedup: u32,

    /// The window over which the value of a link's revenue to our node is calculated.
    #[arg(long, default_value = DEFAULT_REVENUE_WINDOW_SECONDS)]
    pub revenue_window_seconds: u64,

    /// The multiplier applied to revenue_window_seconds to get the duration over which reputation is bootstrapped.
    #[arg(long, default_value = DEFAULT_REPUTATION_MULTIPLIER)]
    pub reputation_multiplier: u8,

    /// The directory to write reputation snapshot file.
    #[arg(long, default_value = DEFAULT_RESULTS_DIR)]
    pub results_dir: PathBuf,

    /// The alias of the target node.
    #[arg(long)]
    pub target_alias: Option<String>,

    /// The alias of the attacking node.
    #[arg(long)]
    pub attacker_alias: Option<String>,
}

impl Cli {
    pub fn reputation_window(&self) -> Duration {
        Duration::from_secs(self.revenue_window_seconds * self.reputation_multiplier as u64)
    }
}

fn parse_duration(s: &str) -> Result<(String, Duration), String> {
    HumanDuration::from_str(s)
        .map(|hd| (s.to_string(), hd.into()))
        .map_err(|e| format!("Invalid duration '{}': {}", s, e))
}

/// Reads forwards from a CSV (generated by simln), optionally filtering to only get a set duration of forwards from
/// the file.
pub async fn history_from_file(
    file_path: &PathBuf,
    filter_duration: Option<Duration>,
) -> Result<Vec<BootstrapForward>, BoxError> {
    let num_chunks = Handle::current().metrics().num_workers().div_ceil(2);
    let breakpoints = calc_file_chunks(file_path, num_chunks as u8)?;

    let file = File::open(file_path)?;
    let file_size = file.metadata()?.len();
    let filter_cutoff = {
        if let Some(duration) = filter_duration {
            let reader = BufReader::new(file);
            let mut csv_reader = csv::Reader::from_reader(reader);
            let mut first_record = StringRecord::new();
            csv_reader.read_record(&mut first_record)?;
            let incoming_add_ts: u64 = first_record[2].parse()?;
            Some(incoming_add_ts.add(duration.as_nanos() as u64))
        } else {
            None
        }
    };

    let mut tasks: Vec<tokio::task::JoinHandle<Result<Vec<BootstrapForward>, BoxError>>> =
        Vec::with_capacity(num_chunks);

    for i in 0..num_chunks {
        let start = breakpoints[i];
        let end = if i == num_chunks - 1 {
            file_size
        } else {
            breakpoints[i + 1]
        };
        let path_clone = file_path.clone();
        tasks.push(task::spawn(async move {
            let mut file = File::open(path_clone)?;
            file.seek(std::io::SeekFrom::Start(start))?;
            let reader = BufReader::new(file).take(end - start);

            let mut csv_reader = if i == 0 {
                csv::Reader::from_reader(reader)
            } else {
                ReaderBuilder::new().has_headers(false).from_reader(reader)
            };

            let mut forwards = Vec::new();
            for result in csv_reader.records() {
                let record: StringRecord = result?;

                // We can skip 6/7 because they're outgoing timestamps, we only care about when the htlc is fully removed
                // from the incoming link (for simplicity's sake).
                let incoming_amt: u64 = record[0].parse()?;
                let incoming_expiry: u32 = record[1].parse()?;
                let incoming_add_ts: u64 = record[2].parse()?;
                let incoming_remove_ts: u64 = record[3].parse()?;
                let outgoing_amt: u64 = record[4].parse()?;
                let outgoing_expiry: u32 = record[5].parse()?;
                let forwarding_node = PublicKey::from_slice(&hex::decode(&record[8])?)?;
                let channel_in_id: u64 = record[10].parse()?;
                let channel_out_id: u64 = record[11].parse()?;

                // If we're filtering cut off any htlc that was in flight at the cutoff point.
                if let Some(cutoff) = filter_cutoff {
                    if incoming_add_ts > cutoff || incoming_remove_ts > cutoff {
                        break;
                    }
                }

                let forward = BootstrapForward {
                    incoming_amt,
                    outgoing_amt,
                    incoming_expiry,
                    outgoing_expiry,
                    added_ns: incoming_add_ts,
                    settled_ns: incoming_remove_ts,
                    forwarding_node,
                    channel_in_id,
                    channel_out_id,
                };

                forwards.push(forward);
            }

            Ok(forwards)
        }));
    }

    let mut forwards = Vec::new();
    for task in tasks {
        let task_forwards = task.await??;
        forwards.extend_from_slice(&task_forwards);
    }

    Ok(forwards)
}
